[package]
name = "tanoshi"
version = "0.22.4"
authors = ["fadhlika"]
edition = "2018"
description = "Tanoshi"
repository = "https://github.com/faldez/tanoshi"
license = "MIT"

[dependencies]
tanoshi-lib = "0.22.0"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.5"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
serde_yaml = "0.8"
warp = {version = "0.3.1", features = ["compression", "tls"]}
rand = {version = "^0.8"}
log = {version = "*"}
pretty_env_logger = {version = "0.4"}
jsonwebtoken = {version = "7"}
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1"
libloading = "^0.7"
rust-embed = {version="5.9", features=["interpolate-folder-path"]}
mime_guess = "2"
clap = "3.0.0-beta.1"
bytes = "1"
dirs = "3"
base64 = "0.13"
lazy_static = "1.4"
async-graphql = { version = "2.8.4", features = [ "apollo_tracing", "chrono" ] }
async-graphql-warp = "2.8.4"
sqlx = { version = "0.5.2", features = [ "runtime-tokio-rustls", "macros", "sqlite", "chrono", "json", "migrate" ] }
reqwest = {version =  "^0.11", features = ["json", "rustls"]}
futures = "^0.3"
rust-argon2 = "0.8"
async-trait = "0.1.50"
rayon = "1.5"